### ISSUE TITLE
python 3.10 numpy bug on macos

### ISSUE THREAD

**Issue by cxwx** [mattpitkin/psrqpy#120]
Hi all,  I found this module is not suitable for python3.10 on macos M1 as same as many other module because of astropy problem.
```
||||||||||||||||||||||||||||||||||||||||||||||||||
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
>>> import psrqpy
>>> q = psrqpy.QueryATNF(params='F0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/psrqpy/search.py", line 216, in __init__
    _ = self.get_catalogue(path_to_db=loadfromdb, cache=cache,
  File "/opt/homebrew/lib/python3.10/site-packages/psrqpy/search.py", line 383, in get_catalogue
    self.set_derived()
  File "/opt/homebrew/lib/python3.10/site-packages/psrqpy/search.py", line 1188, in set_derived
    self.derived_ecliptic()  # derive the ecliptic coordinates if not given
  File "/opt/homebrew/lib/python3.10/site-packages/psrqpy/search.py", line 1483, in derived_ecliptic
    ).transform_to(BarycentricMeanEcliptic())
  File "/opt/homebrew/lib/python3.10/site-packages/astropy/coordinates/baseframe.py", line 1205, in transform_to
    return trans(self, new_frame)
  File "/opt/homebrew/lib/python3.10/site-packages/astropy/coordinates/transformations.py", line 1479, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/opt/homebrew/lib/python3.10/site-packages/astropy/coordinates/transformations.py", line 1252, in __call__
    newrep = self._apply_transform(fromcoord, *params)
  File "/opt/homebrew/lib/python3.10/site-packages/astropy/coordinates/transformations.py", line 1174, in _apply_transform
    rep = rep.transform(matrix)
  File "/opt/homebrew/lib/python3.10/site-packages/astropy/coordinates/representation.py", line 1399, in transform
    p = erfa_ufunc.rxp(matrix, self.get_xyz(xyz_axis=-1))
  File "/opt/homebrew/lib/python3.10/site-packages/astropy/coordinates/representation.py", line 1351, in get_xyz
    return np.stack([self._x, self._y, self._z], axis=xyz_axis)
  File "<__array_function__ internals>", line 200, in stack
  File "/opt/homebrew/lib/python3.10/site-packages/astropy/units/quantity.py", line 1683, in __array_function__
    return super().__array_function__(function, types, args, kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/numpy/core/shape_base.py", line 471, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out,
  File "<__array_function__ internals>", line 200, in concatenate
  File "/opt/homebrew/lib/python3.10/site-packages/astropy/units/quantity.py", line 1688, in __array_function__
    args, kwargs, unit, out = function_helper(*args, **kwargs)
TypeError: concatenate() got an unexpected keyword argument 'dtype'
```

**Comment by mattpitkin** [comment]
Thanks for reporting this. Could you show me what astropy and numpy versions you are using?

I can't reproduce this error in an environment with Python 3.10.9, astropy 5.2.1, and numpy 1.24.1, although that is on a Linux machine. I don't have access to an M1 Mac, so I'll struggle to debug it.

**Comment by mattpitkin** [comment]
I've tried this on an M1 Mac machine now and it seems to work with astropy v5.3 on Python 3.10.11, so I'll close this for now.
